
 /******************************************************************************
 *
 * Module: Dio
 *
 * File Name: port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Dio Driver
 *
 * Author: ahmed zakria
 ******************************************************************************/

#include "port.h"
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
/* PB structure used with port_Init API */
const  Port_ConfigType Port_Configuration  = {
  {portConf_PORT_NUMBER0,portConf_CHANNEL_NUMBER0,portConf_CHANNEL_DIRECTION0,portConf_CHANNEL_INPUT_PIN_MODE0,portConf_CHANNEL_OUTPUT_PIN_MODE0,portConf_CHANNEL_MODE_CHANGAEBLE0,portConf_CHANNEL_DIRECTION_CHANGAEBLE0}, 
  {portConf_PORT_NUMBER1,portConf_CHANNEL_NUMBER1,portConf_CHANNEL_DIRECTION1,portConf_CHANNEL_INPUT_PIN_MODE1,portConf_CHANNEL_OUTPUT_PIN_MODE1,portConf_CHANNEL_MODE_CHANGAEBLE1,portConf_CHANNEL_DIRECTION_CHANGAEBLE1},
  {portConf_PORT_NUMBER2,portConf_CHANNEL_NUMBER2,portConf_CHANNEL_DIRECTION2,portConf_CHANNEL_INPUT_PIN_MODE2,portConf_CHANNEL_OUTPUT_PIN_MODE2,portConf_CHANNEL_MODE_CHANGAEBLE2,portConf_CHANNEL_DIRECTION_CHANGAEBLE2},
  {portConf_PORT_NUMBER3,portConf_CHANNEL_NUMBER3,portConf_CHANNEL_DIRECTION3,portConf_CHANNEL_INPUT_PIN_MODE3,portConf_CHANNEL_OUTPUT_PIN_MODE3,portConf_CHANNEL_MODE_CHANGAEBLE3,portConf_CHANNEL_DIRECTION_CHANGAEBLE3},
  {portConf_PORT_NUMBER4,portConf_CHANNEL_NUMBER4,portConf_CHANNEL_DIRECTION4,portConf_CHANNEL_INPUT_PIN_MODE4,portConf_CHANNEL_OUTPUT_PIN_MODE4,portConf_CHANNEL_MODE_CHANGAEBLE4,portConf_CHANNEL_DIRECTION_CHANGAEBLE4},
  {portConf_PORT_NUMBER5,portConf_CHANNEL_NUMBER5,portConf_CHANNEL_DIRECTION5,portConf_CHANNEL_INPUT_PIN_MODE5,portConf_CHANNEL_OUTPUT_PIN_MODE5,portConf_CHANNEL_MODE_CHANGAEBLE5,portConf_CHANNEL_DIRECTION_CHANGAEBLE5},
  {portConf_PORT_NUMBER6,portConf_CHANNEL_NUMBER6,portConf_CHANNEL_DIRECTION6,portConf_CHANNEL_INPUT_PIN_MODE6,portConf_CHANNEL_OUTPUT_PIN_MODE6,portConf_CHANNEL_MODE_CHANGAEBLE6,portConf_CHANNEL_DIRECTION_CHANGAEBLE6},
  {portConf_PORT_NUMBER7,portConf_CHANNEL_NUMBER7,portConf_CHANNEL_DIRECTION7,portConf_CHANNEL_INPUT_PIN_MODE7,portConf_CHANNEL_OUTPUT_PIN_MODE7,portConf_CHANNEL_MODE_CHANGAEBLE7,portConf_CHANNEL_DIRECTION_CHANGAEBLE7},
  {portConf_PORT_NUMBER8,portConf_CHANNEL_NUMBER8,portConf_CHANNEL_DIRECTION8,portConf_CHANNEL_INPUT_PIN_MODE8,portConf_CHANNEL_OUTPUT_PIN_MODE8,portConf_CHANNEL_MODE_CHANGAEBLE8,portConf_CHANNEL_DIRECTION_CHANGAEBLE8},
  {portConf_PORT_NUMBER9,portConf_CHANNEL_NUMBER9,portConf_CHANNEL_DIRECTION9,portConf_CHANNEL_INPUT_PIN_MODE9,portConf_CHANNEL_OUTPUT_PIN_MODE9,portConf_CHANNEL_MODE_CHANGAEBLE9,portConf_CHANNEL_DIRECTION_CHANGAEBLE9},                                          
  {portConf_PORT_NUMBER10,portConf_CHANNEL_NUMBER10,portConf_CHANNEL_DIRECTION10,portConf_CHANNEL_INPUT_PIN_MODE10,portConf_CHANNEL_OUTPUT_PIN_MODE10,portConf_CHANNEL_MODE_CHANGAEBLE10,portConf_CHANNEL_DIRECTION_CHANGAEBLE10},
  {portConf_PORT_NUMBER11,portConf_CHANNEL_NUMBER11,portConf_CHANNEL_DIRECTION11,portConf_CHANNEL_INPUT_PIN_MODE11,portConf_CHANNEL_OUTPUT_PIN_MODE11,portConf_CHANNEL_MODE_CHANGAEBLE11,portConf_CHANNEL_DIRECTION_CHANGAEBLE11},
  {portConf_PORT_NUMBER12,portConf_CHANNEL_NUMBER12,portConf_CHANNEL_DIRECTION12,portConf_CHANNEL_INPUT_PIN_MODE12,portConf_CHANNEL_OUTPUT_PIN_MODE12,portConf_CHANNEL_MODE_CHANGAEBLE12,portConf_CHANNEL_DIRECTION_CHANGAEBLE12},
  {portConf_PORT_NUMBER13,portConf_CHANNEL_NUMBER13,portConf_CHANNEL_DIRECTION13,portConf_CHANNEL_INPUT_PIN_MODE13,portConf_CHANNEL_OUTPUT_PIN_MODE13,portConf_CHANNEL_MODE_CHANGAEBLE13,portConf_CHANNEL_DIRECTION_CHANGAEBLE13},
  {portConf_PORT_NUMBER14,portConf_CHANNEL_NUMBER14,portConf_CHANNEL_DIRECTION14,portConf_CHANNEL_INPUT_PIN_MODE14,portConf_CHANNEL_OUTPUT_PIN_MODE14,portConf_CHANNEL_MODE_CHANGAEBLE14,portConf_CHANNEL_DIRECTION_CHANGAEBLE14},
  {portConf_PORT_NUMBER15,portConf_CHANNEL_NUMBER15,portConf_CHANNEL_DIRECTION15,portConf_CHANNEL_INPUT_PIN_MODE15,portConf_CHANNEL_OUTPUT_PIN_MODE15,portConf_CHANNEL_MODE_CHANGAEBLE15,portConf_CHANNEL_DIRECTION_CHANGAEBLE15},
  {portConf_PORT_NUMBER16,portConf_CHANNEL_NUMBER16,portConf_CHANNEL_DIRECTION16,portConf_CHANNEL_INPUT_PIN_MODE16,portConf_CHANNEL_OUTPUT_PIN_MODE16,portConf_CHANNEL_MODE_CHANGAEBLE16,portConf_CHANNEL_DIRECTION_CHANGAEBLE16},
  {portConf_PORT_NUMBER17,portConf_CHANNEL_NUMBER17,portConf_CHANNEL_DIRECTION17,portConf_CHANNEL_INPUT_PIN_MODE17,portConf_CHANNEL_OUTPUT_PIN_MODE17,portConf_CHANNEL_MODE_CHANGAEBLE17,portConf_CHANNEL_DIRECTION_CHANGAEBLE17},
  {portConf_PORT_NUMBER18,portConf_CHANNEL_NUMBER18,portConf_CHANNEL_DIRECTION18,portConf_CHANNEL_INPUT_PIN_MODE18,portConf_CHANNEL_OUTPUT_PIN_MODE18,portConf_CHANNEL_MODE_CHANGAEBLE18,portConf_CHANNEL_DIRECTION_CHANGAEBLE18},
  {portConf_PORT_NUMBER19,portConf_CHANNEL_NUMBER19,portConf_CHANNEL_DIRECTION19,portConf_CHANNEL_INPUT_PIN_MODE19,portConf_CHANNEL_OUTPUT_PIN_MODE19,portConf_CHANNEL_MODE_CHANGAEBLE19,portConf_CHANNEL_DIRECTION_CHANGAEBLE19},
  {portConf_PORT_NUMBER20,portConf_CHANNEL_NUMBER20,portConf_CHANNEL_DIRECTION20,portConf_CHANNEL_INPUT_PIN_MODE20,portConf_CHANNEL_OUTPUT_PIN_MODE20,portConf_CHANNEL_MODE_CHANGAEBLE20,portConf_CHANNEL_DIRECTION_CHANGAEBLE20},
  {portConf_PORT_NUMBER21,portConf_CHANNEL_NUMBER21,portConf_CHANNEL_DIRECTION21,portConf_CHANNEL_INPUT_PIN_MODE21,portConf_CHANNEL_OUTPUT_PIN_MODE21,portConf_CHANNEL_MODE_CHANGAEBLE21,portConf_CHANNEL_DIRECTION_CHANGAEBLE21},
  {portConf_PORT_NUMBER22,portConf_CHANNEL_NUMBER22,portConf_CHANNEL_DIRECTION22,portConf_CHANNEL_INPUT_PIN_MODE22,portConf_CHANNEL_OUTPUT_PIN_MODE22,portConf_CHANNEL_MODE_CHANGAEBLE22,portConf_CHANNEL_DIRECTION_CHANGAEBLE22},
  {portConf_PORT_NUMBER23,portConf_CHANNEL_NUMBER23,portConf_CHANNEL_DIRECTION23,portConf_CHANNEL_INPUT_PIN_MODE23,portConf_CHANNEL_OUTPUT_PIN_MODE23,portConf_CHANNEL_MODE_CHANGAEBLE23,portConf_CHANNEL_DIRECTION_CHANGAEBLE23},
  {portConf_PORT_NUMBER24,portConf_CHANNEL_NUMBER24,portConf_CHANNEL_DIRECTION24,portConf_CHANNEL_INPUT_PIN_MODE24,portConf_CHANNEL_OUTPUT_PIN_MODE24,portConf_CHANNEL_MODE_CHANGAEBLE24,portConf_CHANNEL_DIRECTION_CHANGAEBLE24},
  {portConf_PORT_NUMBER25,portConf_CHANNEL_NUMBER25,portConf_CHANNEL_DIRECTION25,portConf_CHANNEL_INPUT_PIN_MODE25,portConf_CHANNEL_OUTPUT_PIN_MODE25,portConf_CHANNEL_MODE_CHANGAEBLE25,portConf_CHANNEL_DIRECTION_CHANGAEBLE25},
  {portConf_PORT_NUMBER26,portConf_CHANNEL_NUMBER26,portConf_CHANNEL_DIRECTION26,portConf_CHANNEL_INPUT_PIN_MODE26,portConf_CHANNEL_OUTPUT_PIN_MODE26,portConf_CHANNEL_MODE_CHANGAEBLE26,portConf_CHANNEL_DIRECTION_CHANGAEBLE26},
  {portConf_PORT_NUMBER27,portConf_CHANNEL_NUMBER27,portConf_CHANNEL_DIRECTION27,portConf_CHANNEL_INPUT_PIN_MODE27,portConf_CHANNEL_OUTPUT_PIN_MODE27,portConf_CHANNEL_MODE_CHANGAEBLE27,portConf_CHANNEL_DIRECTION_CHANGAEBLE27},
  {portConf_PORT_NUMBER28,portConf_CHANNEL_NUMBER28,portConf_CHANNEL_DIRECTION28,portConf_CHANNEL_INPUT_PIN_MODE28,portConf_CHANNEL_OUTPUT_PIN_MODE28,portConf_CHANNEL_MODE_CHANGAEBLE28,portConf_CHANNEL_DIRECTION_CHANGAEBLE28},
  {portConf_PORT_NUMBER29,portConf_CHANNEL_NUMBER29,portConf_CHANNEL_DIRECTION29,portConf_CHANNEL_INPUT_PIN_MODE29,portConf_CHANNEL_OUTPUT_PIN_MODE29,portConf_CHANNEL_MODE_CHANGAEBLE29,portConf_CHANNEL_DIRECTION_CHANGAEBLE29},
  {portConf_PORT_NUMBER30,portConf_CHANNEL_NUMBER30,portConf_CHANNEL_DIRECTION30,portConf_CHANNEL_INPUT_PIN_MODE30,portConf_CHANNEL_OUTPUT_PIN_MODE30,portConf_CHANNEL_MODE_CHANGAEBLE30,portConf_CHANNEL_DIRECTION_CHANGAEBLE30},
  {portConf_PORT_NUMBER31,portConf_CHANNEL_NUMBER31,portConf_CHANNEL_DIRECTION31,portConf_CHANNEL_INPUT_PIN_MODE31,portConf_CHANNEL_OUTPUT_PIN_MODE31,portConf_CHANNEL_MODE_CHANGAEBLE31,portConf_CHANNEL_DIRECTION_CHANGAEBLE31},
  {portConf_PORT_NUMBER32,portConf_CHANNEL_NUMBER32,portConf_CHANNEL_DIRECTION32,portConf_CHANNEL_INPUT_PIN_MODE32,portConf_CHANNEL_OUTPUT_PIN_MODE32,portConf_CHANNEL_MODE_CHANGAEBLE32,portConf_CHANNEL_DIRECTION_CHANGAEBLE32},
  {portConf_PORT_NUMBER33,portConf_CHANNEL_NUMBER33,portConf_CHANNEL_DIRECTION33,portConf_CHANNEL_INPUT_PIN_MODE33,portConf_CHANNEL_OUTPUT_PIN_MODE33,portConf_CHANNEL_MODE_CHANGAEBLE33,portConf_CHANNEL_DIRECTION_CHANGAEBLE33},
  {portConf_PORT_NUMBER34,portConf_CHANNEL_NUMBER34,portConf_CHANNEL_DIRECTION34,portConf_CHANNEL_INPUT_PIN_MODE34,portConf_CHANNEL_OUTPUT_PIN_MODE34,portConf_CHANNEL_MODE_CHANGAEBLE34,portConf_CHANNEL_DIRECTION_CHANGAEBLE34},
  {portConf_PORT_NUMBER35,portConf_CHANNEL_NUMBER35,portConf_CHANNEL_DIRECTION35,portConf_CHANNEL_INPUT_PIN_MODE35,portConf_CHANNEL_OUTPUT_PIN_MODE35,portConf_CHANNEL_MODE_CHANGAEBLE35,portConf_CHANNEL_DIRECTION_CHANGAEBLE35},
  {portConf_PORT_NUMBER36,portConf_CHANNEL_NUMBER36,portConf_CHANNEL_DIRECTION36,portConf_CHANNEL_INPUT_PIN_MODE36,portConf_CHANNEL_OUTPUT_PIN_MODE36,portConf_CHANNEL_MODE_CHANGAEBLE36,portConf_CHANNEL_DIRECTION_CHANGAEBLE36},
  {portConf_PORT_NUMBER37,portConf_CHANNEL_NUMBER37,portConf_CHANNEL_DIRECTION37,portConf_CHANNEL_INPUT_PIN_MODE37,portConf_CHANNEL_OUTPUT_PIN_MODE37,portConf_CHANNEL_MODE_CHANGAEBLE37,portConf_CHANNEL_DIRECTION_CHANGAEBLE37},
  {portConf_PORT_NUMBER38,portConf_CHANNEL_NUMBER38,portConf_CHANNEL_DIRECTION38,portConf_CHANNEL_INPUT_PIN_MODE38,portConf_CHANNEL_OUTPUT_PIN_MODE38,portConf_CHANNEL_MODE_CHANGAEBLE38,portConf_CHANNEL_DIRECTION_CHANGAEBLE38},
  {portConf_PORT_NUMBER39,portConf_CHANNEL_NUMBER39,portConf_CHANNEL_DIRECTION39,portConf_CHANNEL_INPUT_PIN_MODE39,portConf_CHANNEL_OUTPUT_PIN_MODE39,portConf_CHANNEL_MODE_CHANGAEBLE39,portConf_CHANNEL_DIRECTION_CHANGAEBLE39},
  {portConf_PORT_NUMBER40,portConf_CHANNEL_NUMBER40,portConf_CHANNEL_DIRECTION40,portConf_CHANNEL_INPUT_PIN_MODE40,portConf_CHANNEL_OUTPUT_PIN_MODE40,portConf_CHANNEL_MODE_CHANGAEBLE40,portConf_CHANNEL_DIRECTION_CHANGAEBLE40},
  {portConf_PORT_NUMBER41,portConf_CHANNEL_NUMBER41,portConf_CHANNEL_DIRECTION41,portConf_CHANNEL_INPUT_PIN_MODE41,portConf_CHANNEL_OUTPUT_PIN_MODE41,portConf_CHANNEL_MODE_CHANGAEBLE41,portConf_CHANNEL_DIRECTION_CHANGAEBLE41},
  {portConf_PORT_NUMBER42,portConf_CHANNEL_NUMBER42,portConf_CHANNEL_DIRECTION42,portConf_CHANNEL_INPUT_PIN_MODE42,portConf_CHANNEL_OUTPUT_PIN_MODE42,portConf_CHANNEL_MODE_CHANGAEBLE42,portConf_CHANNEL_DIRECTION_CHANGAEBLE42}
};                                         
